import type { Lead } from "@/types/lead";

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number, hour = 11, minute = 20): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

/** Seed aligned with HTML prototype (ISO timestamps for runtime). */
export const MOCK_LEADS: Lead[] = [
  {
    id: "l1",
    name: "Ahmed Hassan",
    company: "Qatar Events Group",
    position: "Operations Manager",
    phone: "+974 5555 1234",
    email: "ahmed@company.com",
    interest: "WhatsApp AI",
    priority: "Hot",
    owner: "Rajan",
    notes: "Wants a demo next week. Decision maker.",
    business_card_image: null,
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
  {
    id: "l2",
    name: "Sarah John",
    company: "ABC Holdings",
    position: "Head of Customer Care",
    phone: "+974 5555 5678",
    email: "sarah@abc.com",
    interest: "Contact Center",
    priority: "Warm",
    owner: "Nicole",
    notes: "Reviewing vendors this quarter.",
    business_card_image: null,
    created_at: hoursAgo(1.5),
    updated_at: hoursAgo(1.5),
  },
  {
    id: "l3",
    name: "Mohammed Al Kuwari",
    company: "Doha Leisure Co.",
    position: "Director",
    phone: "+974 3312 8890",
    email: "m.alkuwari@dohaleisure.qa",
    interest: "FEC Solutions",
    priority: "Hot",
    owner: "Waqar",
    notes: "Opening a new FEC in Lusail.",
    business_card_image: null,
    created_at: hoursAgo(3),
    updated_at: hoursAgo(3),
  },
  {
    id: "l4",
    name: "Priya Nair",
    company: "Gulf Retail Partners",
    position: "Marketing Lead",
    phone: "+974 7788 2211",
    email: "priya@gulfretail.com",
    interest: "Events",
    priority: "Warm",
    owner: "Mary",
    notes: "Planning an activation for Q2.",
    business_card_image: null,
    created_at: hoursAgo(4.5),
    updated_at: hoursAgo(4.5),
  },
  {
    id: "l5",
    name: "Khalid Al Mansoori",
    company: "Msheireb Ventures",
    position: "Business Development",
    phone: "+974 5544 9087",
    email: "khalid@msheirebv.qa",
    interest: "Partnership",
    priority: "Hot",
    owner: "Rajan",
    notes: "Reseller partnership across GCC.",
    business_card_image: null,
    created_at: hoursAgo(5.5),
    updated_at: hoursAgo(5.5),
  },
  {
    id: "l6",
    name: "Laila Ibrahim",
    company: "Al Rayyan Media",
    position: "Account Director",
    phone: "+974 6611 4432",
    email: "laila@alrayyanmedia.qa",
    interest: "Contact Center",
    priority: "Cold",
    owner: "Nicole",
    notes: "Collecting information only.",
    business_card_image: null,
    created_at: hoursAgo(6.5),
    updated_at: hoursAgo(6.5),
  },
  {
    id: "l7",
    name: "Daniel Cruz",
    company: "Pearl Hospitality",
    position: "IT Manager",
    phone: "+974 3390 7765",
    email: "daniel.cruz@pearlhosp.com",
    interest: "WhatsApp AI",
    priority: "Warm",
    owner: "Waqar",
    notes: "Needs PMS integration details.",
    business_card_image: null,
    created_at: daysAgo(1, 16, 40),
    updated_at: daysAgo(1, 16, 40),
  },
  {
    id: "l8",
    name: "Fatima Al Thani",
    company: "Qatar Family Fun",
    position: "General Manager",
    phone: "+974 5501 3344",
    email: "fatima@qff.qa",
    interest: "FEC Solutions",
    priority: "Hot",
    owner: "Mary",
    notes: "Two sites, wants pricing by Sunday.",
    business_card_image: null,
    created_at: daysAgo(1, 15, 15),
    updated_at: daysAgo(1, 15, 15),
  },
  {
    id: "l9",
    name: "Rakesh Menon",
    company: "Lusail Logistics",
    position: "Customer Service Head",
    phone: "+974 7712 6650",
    email: "rakesh@lusaillog.com",
    interest: "Contact Center",
    priority: "Warm",
    owner: "Rajan",
    notes: "Currently on a legacy system.",
    business_card_image: null,
    created_at: daysAgo(1, 14, 5),
    updated_at: daysAgo(1, 14, 5),
  },
  {
    id: "l10",
    name: "Noora Al Sulaiti",
    company: "Souq Waqif Group",
    position: "Events Manager",
    phone: "+974 6650 1198",
    email: "noora@swgroup.qa",
    interest: "Events",
    priority: "Cold",
    owner: "Nicole",
    notes: "Follow up after the show.",
    business_card_image: null,
    created_at: daysAgo(1, 12, 20),
    updated_at: daysAgo(1, 12, 20),
  },
];
